# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="shellcraft2"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github git-extras svn vi-mode node npm extract zsh-syntax-highlighting autojump vagrant xp-ant-ivy zsh-xpframework encode64 urltools mvn coffee sublime bower)
[[ -e "/etc/zsh_command_not_found" ]] && plugins+=(command-not-found)
[[ -e "/etc/debian_version" ]] && plugins+=(deb debian)
[[ $(uname) == Darwin ]] && plugins+=(osx brew)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
ZSH_CUSTOM=$HOME/.oh-my-zsh.custom

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Treat the `#', `~' and `^' characters as part of patterns for filename generation, etc.
# (An initial unquoted `~' always produces named directory expansion.)
# unset because ob git .. HEAD^ problems
#setopt extendedglob

# use ctrl-r for history search backward, like bash in vi-mode
bindkey '^R' history-incremental-search-backward
# vim mode of backspace or use X in normal mode
bindkey '^?' backward-delete-char

# load RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Show completion description
zstyle ":completion:*:descriptions" format "%B%d%b"


#. $HOME/Documents/src/powerline/powerline/bindings/zsh/powerline.zsh
