#!/bin/bash

host=192.168.50.1
port=51235
localroot='/mnt/dev/'
file=`realpath $1`
file=${file/$localroot/''}
curl "http://$host:$port/?file=$file"

# NODEJS version
# #!/usr/bin/env coffee
# 
# localroot = '/Users/kuse/devel/'
# http = require('http')
# fs = require 'fs'
# filename = process.argv[2]
# 
# options = 
#   host: '127.0.0.1'
#   port: 8000
#   method: 'GET'
# 
# fs.realpath filename, (err, resolvedPath) ->
#   throw err if err
#   file = resolvedPath.replace localroot, ''
#   console.log file
#   options.path = '/?file=' + file
#   console.log options
#   http.request(options).end()
